### ISSUE TITLE
Review OS's

### ISSUE THREAD

**Issue by markbrown87** [cwsamuelson/OS#4]

**Comment by markbrown87** [comment]
Review OS basics. This might mean reading from different sources to understand exactly what the next steps will be.

**Comment by markbrown87** [comment]
@cwsamuelson I accidentally closed this ticket but re-opened it. I also noticed that I am unable to modify things like Assignees or Labels -- is this permissions thing? My previous Project didn't have this issue but I also created it.

**Comment by cwsamuelson** [comment]
Uhm, actually you should create a separate ticket for fixing your permissions.
JK, I invited you to collaborate on the repo.
Your perms were set in the GK board, but not the GH repo
